title: "Replication Package for CoLiCo"
description: "<b>Replication Package for Our Paper:</b><br>Beyond Literal Meaning: Uncover and Explain Implicit Knowledge in Code through Wikipedia-based Concept Linking"
theme: jekyll-theme-cayman
